sudo: required 
language: generic
services: 
    - docker

before_install:
    - docker build -t jhharwood88/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jhharwood88/docker-react npm run test